### PR TITLE
Bugfix vmbdali

### LINKED ISSUE #114: Regression for VMBDALI starting at 2024.7.0
Hi,

Since version I am [2024.7.0](https://github.com/Cereal2nd/velbus-aio/compare/2024.6.0...2024.7.0) no longer able to use my 'old' VMBDALI module anymore. In another location an updated VMBDALI-20 seems to load, but is not showing any channels with version >2024.7.0.

```
INFO:velbus-handler:No cache yet, so forcing a bus scan
INFO:velbus-handler:Start module scan
INFO:velbus-handler:Starting handling scan 1
INFO:velbus-handler:Starting scan 1
INFO:velbus:Found module 1: <{} type:69 address:1 loaded:False loading:False channels: {}>
DEBUG:velbus-handler:Module 1 detected: start loading
INFO:velbus-handler:Scan module 1 completed, module loaded=True
INFO:velbus-handler:Starting handling scan 2
INFO:velbus-handler:Starting scan 2
```

Same scan on same version ( and same requirements.txt ) on another location with a VMBDALI-20 seems to work up to module level, but is not loading any channels.

```
INFO:velbus-handler:No cache yet, so forcing a bus scan
INFO:velbus-handler:Start module scan
INFO:velbus-handler:Starting handling scan 1
INFO:velbus-handler:Starting scan 1
INFO:velbus:Found module 1: <{} type:90 address:1 loaded:False loading:False channels: {}>
DEBUG:velbus-handler:Module 1 detected: start loading
INFO:velbus-handler:Scan module 1 completed, module loaded=True
INFO:velbus-handler:Starting handling scan 2
INFO:velbus-handler:Starting scan 2
...
...
<None type:90 address:1 loaded:True loading:False channels: {}>

<None type:90 address:1 loaded:True loading:False channels: {}>

<None type:90 address:1 loaded:True loading:False channels: {}>

<None type:90 address:1 loaded:True loading:False channels: {}>

```

Is module type '69' no longer detected as a VMBDALI and where's the channels?

Please advise, let me know what else I can do to help and thanks in advance!

### PR DESCRIPTION
**Pull request by niobos**
WARNING: WORK IN PROGRESS
I haven't tested this on my installation yet

This should fix #114. 
It also adds a very basic test that should catch this in the future.

### CODE REVIEW

**Review by Cereal2nd — APPROVED** [review]

**Comment by dverhelst** [comment]
@niobos , can I be of assistance testing VMBDALI and VMBDALI-20 going forward?

**Comment by niobos** [comment]
I still need to test the changes on an actual installation that has the VMBDALI modules. Currently, I can't access it, but I should be able to in the next few weeks. If you know how to run Home Assistant with a development version of velbus-aio, you can try it and report back.

**Comment by niobos** [comment]
I can confirm that these changes fix the VMBDALI (1st version, not -20) in my installation.

What needs to happen next is that @Cereal2nd needs to release a new version of this library, and this new release needs to be referenced from the Home Assistant code. This is fairly straight-forward, but requires some manual work.

**Comment by Cereal2nd** [comment]
the pull-request has been created

**Pull request merged**
